### ISSUE TITLE
catalog window width issue

### ISSUE THREAD

**Issue by brendaniel** [yanm1ng/hexo-theme-vexo#54]
When using catalog function, window width is overflowed.

![image](https://user-images.githubusercontent.com/11773683/32849506-a7c093a6-ca72-11e7-8ebb-2e8b4a942d46.png)

I have not modified css.
``` css
.catalog-container {
    display: block;
    margin-left: 20px;
    flex-basis: 280px;
    -webkit-flex-basis: 280px;
    flex-shrink: 0;
    -webkit-flex-shrink: 0;
}

.catalog-container .toc-main {
    padding-left: 20px;
    border-left: 1px solid #dadada;
    width: 280px;
    box-sizing: border-box;
}
```

Same thing happens on mobile.
